### PR TITLE
all: gofmt with Go 1.19

### PR DESCRIPTION
**Pull request by charlievieth**
Go 1.19 adds doc comments. This commit runs `gofmt` on all the code to update the comments.

https://tip.golang.org/doc/go1.19#go-doc

### CODE REVIEW

**Comment by dylan-bourque** [comment]
Changes seem 👍 on the surface.  What does the updated godoc actually look like, @charlievieth?  It should be fine since the indented blocks should render well in 1.18 or earlier but it's best to verify before moving forward.

**Comment by charlievieth** [comment]
Verified that there is no change in presentation (I think pkg.go.dev might already be applying these changes - all that `gofmt` is now doing is trying to make the "semantic meaning" of comments clearer).

The changes here are just the result of `gofmt` (as of 1.19) adjusting the code blocks to match the expected format (there is also one change that adds the new build tag format but thats been around for a bit).

See the "Code Blocks" section of [doc/comment](https://tip.golang.org/doc/comment) for more information.

**Review by dylan-bourque — APPROVED** [review]

**Comment by cameracker** [comment]
@charlievieth  thanks for taking the time to clean up the code here. Would you mind rerunning this against tip master? It looks like the major rework PR yielded some conflicts 👍

**Comment by charlievieth** [comment]
> @charlievieth thanks for taking the time to clean up the code here. Would you mind rerunning this against tip master? It looks like the major rework PR yielded some conflicts 👍

Done and thanks for the quick review.

**Pull request merged**
