### PR TITLE
uuid.Equal

### PR DESCRIPTION
**Pull request by rocketbitz**
Implements `uuid.Equal` method.

### CODE REVIEW

**Comment by rocketbitz** [comment]
I see. Apologies, I didn't see https://github.com/gofrs/uuid/pull/36. Was purely in the effort to make things easier for people to switch from legacy satori uuid, something I am doing right now.

**Comment by CameronAckermanSEL** [comment]
2.0.0 is a drop in replacement for what is on satori/go.uuid@master

**Comment by theckman** [comment]
@rocketbitz `v2.x` should be easier to migrate to, it's API compatible with the current master branch of https://github.com/satori/go.uuid. Here's the latest `v2.x` release:

- https://github.com/gofrs/uuid/releases/tag/v2.1.0

**Comment by jadr2ddude** [comment]
@rocketbitz v2.x is compatible with satori UUID (and contains the equal function). The 3.x versions break compatibility slightly in order to simplify the API. Closing.

**Comment by rocketbitz** [comment]
Appreciate it guys, and thanks for maintaining this.

**Pull request closed without merging**
