### PR TITLE
sql: assert UUID satisfies the driver.Valuer and sql.Scanner interfaces

### PR DESCRIPTION
**Pull request by charlievieth**

### CODE REVIEW

**Comment by 17twenty** [comment]
Related to https://github.com/gofrs/uuid/pull/108 I assume?

**Comment by charlievieth** [comment]
> Related to #108 I assume?

Yes, should have made that clearer.

**Review by cameracker — APPROVED** [review]

**Comment by cameracker** [comment]
I'll give some other folks a chance to comment but i'll merge within the next few days. Thank you very much @charlievieth !

**Comment by dylan-bourque** [comment]
👍 from me

**Pull request merged**
