### PR TITLE
build: replace coveralls with codecov

### PR DESCRIPTION
**Pull request by adamdecaf**
Fixes: https://github.com/gofrs/uuid/issues/55

### CODE REVIEW

**Comment by theckman** [comment]
@acln0 going to venture to say he used the Travis command line tool to configure it.

**Comment by adamdecaf** [comment]
Ah. It was emacs. I'll update the readme.

**Comment by adamdecaf** [comment]
Let's hope codecov retests.

**Comment by acln0** [comment]
That's a strange failure.

**Comment by adamdecaf** [comment]
That's me. The error was just in `go get` for cover. Not our fault.

**Comment by acln0** [comment]
Thanks!

**Pull request merged**
