### PR TITLE
Add go.mod with v3

### PR DESCRIPTION
**Pull request by flibustenet**

### CODE REVIEW

**Comment by flibustenet** [comment]
For #43

**Comment by jadr2ddude** [comment]
I believe that we should add go 1.11 with modules support to travis. Not sure if that should go here. To do this, we would need to set GO111MODULE=on env variable. We have go tip in travis, so it would run on that.

**Comment by acln0** [comment]
I think 1.11 support to travis should go in a different PR. I filed #45 to that effect.

**Comment by theckman** [comment]
Does `v3` need to be in the file? Why can't the SCM tagging be used to provide the major version? It's provided as metadata on the repo, will be part of the natural release process, and subsequently won't be stale?

**Comment by flibustenet** [comment]
@theckman thanks for your question, i'm not so sure, will look more.

**Comment by flibustenet** [comment]
In the wiki:
https://github.com/golang/go/wiki/Modules#semantic-import-versioning
> If the module is version v2 or higher, the major version of the module must be included in both the module path in the go.mod file (e.g., module example.com/my/mod/v2) and the package import path (e.g., import "example.com/my/mod/v2/foo").

**Comment by flibustenet** [comment]
For the second question, it's maybe related to https://github.com/golang/go/issues/27009 (that confirm in the same time that we need the /v3 in go.mod) ?

**Comment by theckman** [comment]
We may just need to merge this, and deal with the cancer.

**Comment by flibustenet** [comment]
No pressure, it'll still be usable without `go.mod`. Feel free to wait if you think it's to early.

**Comment by acln0** [comment]
I think this can be merged as-is now, unfortunate as the situation may be.

This PR is about v3, but I thought I'd mention that we don't have a `go.mod` for v2, and I don't know how easy it would be to backport one, or if we even care to do so. In the meantime, module users who want v2 can `go get github.com/gofrs/uuid@v2.1.0` and they'll get a `require github.com/gofrs/uuid v2.1.0+incompatible` in their `go.mod`. Oh well.

**Pull request merged**
