### PR TITLE
generator: ensure reads from g.rand are not short

### PR DESCRIPTION
**Pull request by acln0**
Use io.ReadFull to read data from g.rand instead of a single Read call.

### CODE REVIEW

**Comment by theckman** [comment]
@acln0 it's likely I'll need you to rebase this branch once #3 is merged-in. #3 itself is blocked on #6, which has outstanding feedback. Will ping you once #6 and #3 are done.

**Comment by acln0** [comment]
I didn't touch the test code in view of #3, which is good enough, I think. If you still need me to rebase after #3 is done, please ping.

**Comment by theckman** [comment]
@acln0 ignore me, Travis tests on the `merge` branch. I'll rerun it once the merge is done.

**Comment by theckman** [comment]
Recycling PR to get a fresh CI run.

**Pull request merged**
